# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: medusa.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='medusa.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cmedusa.proto\"d\n\rBackupRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x04mode\x18\x02 \x01(\x0e\x32\x13.BackupRequest.Mode\"\"\n\x04Mode\x12\x10\n\x0c\x44IFFERENTIAL\x10\x00\x12\x08\n\x04\x46ULL\x10\x01\"\x10\n\x0e\x42\x61\x63kupResponse23\n\x06Medusa\x12)\n\x06\x42\x61\x63kup\x12\x0e.BackupRequest\x1a\x0f.BackupResponseb\x06proto3'
)



_BACKUPREQUEST_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='BackupRequest.Mode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DIFFERENTIAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FULL', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=82,
  serialized_end=116,
)
_sym_db.RegisterEnumDescriptor(_BACKUPREQUEST_MODE)


_BACKUPREQUEST = _descriptor.Descriptor(
  name='BackupRequest',
  full_name='BackupRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BackupRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mode', full_name='BackupRequest.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BACKUPREQUEST_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=116,
)


_BACKUPRESPONSE = _descriptor.Descriptor(
  name='BackupResponse',
  full_name='BackupResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=134,
)

_BACKUPREQUEST.fields_by_name['mode'].enum_type = _BACKUPREQUEST_MODE
_BACKUPREQUEST_MODE.containing_type = _BACKUPREQUEST
DESCRIPTOR.message_types_by_name['BackupRequest'] = _BACKUPREQUEST
DESCRIPTOR.message_types_by_name['BackupResponse'] = _BACKUPRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BackupRequest = _reflection.GeneratedProtocolMessageType('BackupRequest', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPREQUEST,
  '__module__' : 'medusa_pb2'
  # @@protoc_insertion_point(class_scope:BackupRequest)
  })
_sym_db.RegisterMessage(BackupRequest)

BackupResponse = _reflection.GeneratedProtocolMessageType('BackupResponse', (_message.Message,), {
  'DESCRIPTOR' : _BACKUPRESPONSE,
  '__module__' : 'medusa_pb2'
  # @@protoc_insertion_point(class_scope:BackupResponse)
  })
_sym_db.RegisterMessage(BackupResponse)



_MEDUSA = _descriptor.ServiceDescriptor(
  name='Medusa',
  full_name='Medusa',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=136,
  serialized_end=187,
  methods=[
  _descriptor.MethodDescriptor(
    name='Backup',
    full_name='Medusa.Backup',
    index=0,
    containing_service=None,
    input_type=_BACKUPREQUEST,
    output_type=_BACKUPRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEDUSA)

DESCRIPTOR.services_by_name['Medusa'] = _MEDUSA

# @@protoc_insertion_point(module_scope)
